#!/usr/bin/env python3
"""
merge.py -- build the single-file version of the mod.

WHY THIS EXISTS
---------------
Whether a main.lua mod can dofile() its own .lua files from the MOD/ virtual
root is NOT established by any shipped Teardown mod. The mods/ directory
contains 2838 Lua files and 13 mods with a main.lua entrypoint, and not one of
them loads a sibling .lua that way: the only dofile() calls in the whole corpus
(folkrace) use an absolute path derived from GetString("game.levelpath"), which
is a different mechanism and does not apply here.

main.lua therefore probes candidate paths at runtime and falls back to a
minimal inline bus if none resolve. That fallback keeps the channel alive but
costs the haptics detectors and the camera block.

This script removes the uncertainty entirely: it concatenates the four modules
into one self-contained main.lua that needs no dofile at all. The resulting
file is what you install if the probe fails in the real game.

WHAT IT DOES
------------
  * reads the four source files in dependency order,
  * wraps each in a local scope so they cannot collide,
  * strips nothing and rewrites no logic -- this is a pure concatenation,
  * writes merged/main.lua plus a copy of info.txt and the haptic/ folder.

USAGE
-----
  python3 merge.py
  # then install merged/ as the mod folder
"""

import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Dependency order: the bus has no dependencies, the other three reference it.
# vrinput is last because it is the only module that reads the bus's config
# shape at init time, and it is the one that publishes per-frame intent.
SOURCES = [
    ("vrbus.lua",    "vrbus"),
    ("vrhaptics.lua", "vrhaptics"),
    ("vrcamera.lua",  "vrcamera"),
    ("vrinput.lua",   "vrinput"),
]


def strip_main_callbacks(main_path):
    """
    Return main.lua's body with init/tick/update/draw removed.

    Those four become the mod's entrypoint in the merged file. They are lifted
    to the end of the merged file, outside the module scopes, because the game
    looks them up as globals.

    The match must be anchored to a top-level `function name(...)` with NO
    `local` in front of it. A module that keeps its callbacks local
    (vrinput.lua does, precisely so it cannot clobber the mod's own entrypoint)
    would otherwise be matched first and lifted out, leaving that module
    without a body and the entrypoint wired to the wrong code.
    """
    with open(main_path, "r", encoding="utf-8") as fh:
        src = fh.read()

    callbacks = {}
    for name in ("init", "tick", "update", "draw"):
        # A top-level `function name(...)` ... `end`, explicitly not `local function`.
        pattern = re.compile(
            r"^function\s+" + name + r"\s*\([^)]*\)\s*$\n.*?^end\s*$",
            re.MULTILINE | re.DOTALL,
        )
        match = pattern.search(src)
        if match:
            callbacks[name] = match.group(0)
            src = src[: match.start()] + src[match.end():]

    missing = [n for n in ("init", "tick", "update", "draw") if n not in callbacks]
    if missing:
        raise SystemExit("merge.py: could not find callbacks: %s" % ", ".join(missing))

    return src, callbacks


def main():
    out_dir = os.path.join(HERE, "merged")
    os.makedirs(out_dir, exist_ok=True)

    parts = [
        "--" + "=" * 74,
        "-- Teardown VR -- merged single-file build. GENERATED by merge.py.",
        "--",
        "-- Source of truth is the sibling .lua files; edit those, not this.",
        "-- Regenerate with:  python3 merge.py",
        "--",
        "-- This file exists because dofile() from a main.lua mod is unverified",
        "-- against the real game. Concatenating removes that dependency",
        "-- entirely. Logic is unchanged from the modules.",
        "--" + "=" * 74,
        "",
    ]

    for filename, globalname in SOURCES:
        path = os.path.join(HERE, filename)
        if not os.path.exists(path):
            raise SystemExit("merge.py: missing source %s" % filename)
        with open(path, "r", encoding="utf-8") as fh:
            body = fh.read()
        parts.append(
            "--" + "=" * 74 + "\n-- %s\n--" % filename + "=" * 74 + "\n"
        )
        # Each module is wrapped in its own do/end block. Two reasons, both
        # learned the hard way:
        #
        # 1. A module that keeps its lifecycle callbacks local (vrinput.lua
        #    does, so it cannot clobber the mod's own entrypoint) would
        #    otherwise declare `local function init` at chunk scope. In Lua a
        #    chunk-level local is visible to the END OF THE CHUNK, so the
        #    entrypoint `function init()` appended at the bottom of the merged
        #    file would be captured by that local instead of becoming the
        #    global the game looks up -- the mod would load cleanly and then
        #    never run.
        #
        # 2. Without the block, one module's locals can shadow another's.
        #
        # do/end also guarantees a module cannot return early and make the rest
        # of the file unreachable, which is the other way this breaks.
        parts.append("do  -- %s scope" % filename)
        parts.append(body)
        parts.append("end  -- end %s scope" % filename)
        parts.append("")

    main_path = os.path.join(HERE, "main.lua")
    main_body, callbacks = strip_main_callbacks(main_path)

    parts.append("--" + "=" * 74 + "\n-- main.lua (entrypoint)\n--" + "=" * 74 + "\n")
    parts.append(main_body)
    parts.append("")
    parts.append("--" + "=" * 74 + "\n-- entrypoint callbacks\n--" + "=" * 74 + "\n")
    for name in ("init", "tick", "update", "draw"):
        parts.append(callbacks[name])
        parts.append("")

    merged = "\n".join(parts)
    out_file = os.path.join(out_dir, "main.lua")
    with open(out_file, "w", encoding="utf-8") as fh:
        fh.write(merged)

    # Copy the metadata and the haptic assets so merged/ is a complete mod.
    info_src = os.path.join(HERE, "info.txt")
    if os.path.exists(info_src):
        shutil.copy2(info_src, os.path.join(out_dir, "info.txt"))

    haptic_src = os.path.join(HERE, "haptic")
    if os.path.isdir(haptic_src):
        haptic_dst = os.path.join(out_dir, "haptic")
        if os.path.isdir(haptic_dst):
            shutil.rmtree(haptic_dst)
        shutil.copytree(haptic_src, haptic_dst)

    # A preflight marker so main.lua's probe can short-circuit.
    with open(os.path.join(out_dir, "MERGED_BUILD.txt"), "w", encoding="utf-8") as fh:
        fh.write("This is a merged build. main.lua's dofile probe is bypassed\n"
                 "because all four modules are already inlined above.\n")

    # The actual in-band flag: a global main.lua checks at load time. It has to
    # be set at the TOP of the merged file, because main.lua reads it during
    # its own execution -- and merge.py appends main.lua last.
    with open(out_file, "r", encoding="utf-8") as fh:
        merged_text = fh.read()
    inject = (
        "-- merge.py marker: tells main.lua its modules are already inlined,\n"
        "-- so it must not try to dofile() them.\n"
        "MERGED_BUILD = true\n\n"
    )
    marker_line = "--" + "=" * 74 + "\n"
    idx = merged_text.index(marker_line) + len(marker_line)
    merged_text = merged_text[:idx] + inject + merged_text[idx:]
    with open(out_file, "w", encoding="utf-8") as fh:
        fh.write(merged_text)

    print("wrote %s (%d bytes)" % (out_file, len(merged_text)))
    print("install: copy the contents of merged/ to Teardown/mods/teardown_vr/")


if __name__ == "__main__":
    sys.exit(main())
