--==========================================================================
-- merge.py marker: tells main.lua its modules are already inlined,
-- so it must not try to dofile() them.
MERGED_BUILD = true

-- Teardown VR -- merged single-file build. GENERATED by merge.py.
--
-- Source of truth is the sibling .lua files; edit those, not this.
-- Regenerate with:  python3 merge.py
--
-- This file exists because dofile() from a main.lua mod is unverified
-- against the real game. Concatenating removes that dependency
-- entirely. Logic is unchanged from the modules.
--==========================================================================

--==========================================================================
-- vrbus.lua
--==========================================================================

do  -- vrbus.lua scope
--[[===========================================================================
  vrbus.lua -- Teardown VR: the event / state bus.

  THIS IS THE CONTRACT BETWEEN LUA AND THE NATIVE VR LAYER (teardown_vr.dll).

  The game has no shared-memory bus, no sockets, and no filesystem a mod can
  write to. What it DOES have is a global key/value store exposed to every Lua
  script through SetInt/GetInt, SetFloat/GetFloat, SetBool/GetBool and
  SetString/GetString. That store is the only channel that can carry state out
  of a mod. The native side reads it by locating the same keys in memory.

  Everything here is written so the native side only ever has to read a small,
  fixed set of keys. See docs/LUA_MOD_DESIGN.md for the full protocol.

  ---------------------------------------------------------------------------
  EVENT PROTOCOL (v1)
  ---------------------------------------------------------------------------
  A ring buffer of the most recent VR events is mirrored into the key store at
  a fixed stride. The native side reads:

      "vr.ev.count"   int    number of valid slots in "vr.ev.slot" (0..VRBUS_SLOTS)
      "vr.ev.head"    int    total events ever emitted (monotonic, wraps in Lua)
      "vr.ev.seq"     int    sequence number of the newest event
      "vr.ev.slot.<i>.id"    int   VRBUS id enum (see EV below)
      "vr.ev.slot.<i>.amp"   float 0..1 scaled intensity
      "vr.ev.slot.<i>.ttl"   float seconds the effect should last
      "vr.ev.slot.<i>.hand"  int   0 = both, 1 = left, 2 = right
      "vr.ev.slot.<i>.x"     float world x of the cause (meters)
      "vr.ev.slot.<i>.y"     float world y
      "vr.ev.slot.<i>.z"     float world z
      "vr.ev.slot.<i>.flags" int   VRBUS_FLAG_* bitfield

  The count is what makes this safe to read without locking: the writer only
  publishes an event after its four fields are already written, and it publishes
  the new count LAST. A reader that reads "vr.ev.count" first, then reads only
  slots below that count, can never observe a half-written event. That is the
  whole concurrency contract. No locks, no allocation, no teardown of anything.

  ---------------------------------------------------------------------------
  VERIFIED vs ASSUMED
  ---------------------------------------------------------------------------
  VERIFIED -- every function this file calls is in the game's own API stub file,
  data/script_defs.luau, with a matching signature:
      SetInt(key, value, sync?)      script_defs.luau:643
      GetInt(key)                    script_defs.luau:655
      SetFloat(key, value, sync?)    script_defs.luau:668
      GetFloat(key)                  script_defs.luau:680
      SetBool(key, value, sync?)     script_defs.luau:693
      GetBool(key)                   script_defs.luau:705
      SetString(key, value, sync?)   script_defs.luau:718
      GetString(key)                 script_defs.luau:730
      HasKey(key)                    script_defs.luau:630
      DebugPrint(message)            script_defs.luau:8731
  Their use as a cross-script store is not just allowed but documented -- the
  SetInt doc example is literally `SetInt("score.levels.level1", 4)`, and shipped
  mods read a key that another file wrote (mods/folkrace/config/events.lua:78,86).

  ASSUMED -- see the notes on each item:
    * that the native layer can locate this key store in memory. Not yet
      implemented anywhere in hook/teardown_vr.c. This is the single biggest
      open question in the whole design.
    * that the engine does not resize the key store between our writes and the
      native read. The store is fixed at level load in every shipped mod's usage.
============================================================================]]

VRBUS = VRBUS or {}
VRBUS.__index = VRBUS

-- Number of event slots mirrored into the key store. Power of two so index
-- wrapping is a cheap AND rather than a modulo.
VRBUS_SLOTS = 16

-- Bump when the slot layout changes so the native side can refuse to read a
-- version it was not built against.
VRBUS_PROTOCOL_VERSION = 1

-- Key namespace. Keep short; every event rewrites 6 keys.
VRBUS_PREFIX = "vr.ev."

--[[---------------------------------------------------------------------------
  Event ids. These integers are the stable wire contract -- the native side
  switches on them. Never renumber, only append.
-------------------------------------------------------------------------------]]
VRBUS_EV_NONE          = 0
VRBUS_EV_DAMAGE_TAKEN  = 1   -- the local player lost health
VRBUS_EV_DAMAGE_DEALT  = 2   -- the local player damaged something else
VRBUS_EV_LANDING       = 3   -- the player hit the ground after falling
VRBUS_EV_FALL_START    = 4   -- the player left the ground going downward
VRBUS_EV_TOOL_FIRE     = 5   -- the equipped tool discharged
VRBUS_EV_TOOL_SWITCH   = 6   -- tool changed
VRBUS_EV_TOOL_IMPACT   = 7   -- the held tool struck geometry
VRBUS_EV_EXPLOSION     = 8   -- an explosion within earshot
VRBUS_EV_BREAK         = 9   -- a tracked body was destroyed
VRBUS_EV_GRAB         = 10   -- grabbed / released a body
VRBUS_EV_JUMP         = 11
VRBUS_EV_FOOTSTEP     = 12
VRBUS_EV_VEHICLE_HIT  = 13   -- something struck the vehicle the player drives
VRBUS_EV_VEHICLE_ENTER = 14
VRBUS_EV_VEHICLE_EXIT  = 15
VRBUS_EV_HEARTBEAT    = 16   -- once per second; proves the channel is alive

--[[---------------------------------------------------------------------------
  Event flags (bitfield, OR'd together into slot.flags)
-------------------------------------------------------------------------------]]
VRBUS_FLAG_NONE       = 0
VRBUS_FLAG_SURFACE    = 1     -- struck surface material is known
VRBUS_FLAG_PLAYER     = 2     -- caused by another player
VRBUS_FLAG_EXPLOSIVE  = 4     -- explosive energy involved
VRBUS_FLAG_REMOTE     = 8     -- cause is far from the player
VRBUS_FLAG_REPEAT     = 16    -- suppressed by a repeat-rate limiter

--[[---------------------------------------------------------------------------
  Which controller an event should rumble.
-------------------------------------------------------------------------------]]
VRBUS_HAND_BOTH  = 0
VRBUS_HAND_LEFT  = 1
VRBUS_HAND_RIGHT = 2

local slot  = {}   -- ring buffer index
local count = 0   -- how many slots are currently published
local seq   = 0   -- monotonic event counter

--[[---------------------------------------------------------------------------
  new() -> bus
    Construct a bus. All key names are derived from VRBUS_PREFIX.
-------------------------------------------------------------------------------]]
function VRBUS.new()
  local self = setmetatable({}, VRBUS)
  self.head  = 0
  self.seq   = 0
  self.count = 0
  self.enabled = true
  return self
end

--[[---------------------------------------------------------------------------
  reset()
    Clear the published ring. Called on level load so a stale ring from the
    previous level is never read by the native side.
-------------------------------------------------------------------------------]]
function VRBUS.reset(self)
  self.head  = 0
  self.seq   = 0
  self.count = 0
  SetInt(VRBUS_PREFIX .. "version", VRBUS_PROTOCOL_VERSION)
  SetInt(VRBUS_PREFIX .. "count", 0)
  SetInt(VRBUS_PREFIX .. "head", 0)
  SetInt(VRBUS_PREFIX .. "seq", 0)
end

--[[---------------------------------------------------------------------------
  emit(id, amp, ttl, hand, pos, flags) -> boolean
    Publish one event. amp is clamped to 0..1, ttl is clamped to >= 0.

    Returns true if the event was published, false if it was dropped (disabled
    or degenerate amplitude).

    Ordering matters and is part of the contract: fields first, count last.
-------------------------------------------------------------------------------]]
function VRBUS.emit(self, id, amp, ttl, hand, pos, flags)
  if not self.enabled then return false end
  if id == nil or id == VRBUS_EV_NONE then return false end

  amp = tonumber(amp) or 0.0
  if amp <= 0.0 then return false end
  if amp > 1.0 then amp = 1.0 end

  ttl = tonumber(ttl) or 0.0
  if ttl < 0.0 then ttl = 0.0 end

  flags = flags or VRBUS_FLAG_NONE
  hand  = hand or VRBUS_HAND_BOTH

  local x, y, z = 0.0, 0.0, 0.0
  if pos ~= nil then
    x = tonumber(pos[1]) or 0.0
    y = tonumber(pos[2]) or 0.0
    z = tonumber(pos[3]) or 0.0
  end

  self.head  = (self.head + 1) % VRBUS_SLOTS
  self.seq   = self.seq + 1
  local base = VRBUS_PREFIX .. "slot." .. self.head .. "."

  -- Payload first. A reader gated on "count" cannot see these until it is set.
  SetInt(base .. "id",    id)
  SetFloat(base .. "amp",  amp)
  SetFloat(base .. "ttl",  ttl)
  SetInt(base .. "hand",   hand)
  SetFloat(base .. "x",    x)
  SetFloat(base .. "y",    y)
  SetFloat(base .. "z",    z)
  SetInt(base .. "flags",  flags)

  -- Publish LAST. This is the release store the native side reads first.
  self.count = self.count + 1
  if self.count > VRBUS_SLOTS then self.count = VRBUS_SLOTS end
  SetInt(VRBUS_PREFIX .. "count", self.count)
  SetInt(VRBUS_PREFIX .. "head",  self.head)
  SetInt(VRBUS_PREFIX .. "seq",   self.seq)
  return true
end

--[[---------------------------------------------------------------------------
  Rate limiting. Explosions and impacts cluster; without this the controller
  motors get a buzz that reads as static rather than as an event.
  Returns true if the caller should proceed.
-------------------------------------------------------------------------------]]
function VRBUS.allow(self, id, minInterval, now)
  if not self._last then self._last = {} end
  local prev = self._last[id]
  if prev ~= nil and (now - prev) < minInterval then
    self._suppressed = self._suppressed + 1
    return false
  end
  self._last[id] = now
  return true
end

--[[---------------------------------------------------------------------------
  setKey / getKey -- generic scalar channel, same store, for values that are
  not events (VR state, user settings). Same publish-last discipline.
-------------------------------------------------------------------------------]]
function VRBUS.setFloat(self, name, value)
  SetFloat("vr.val." .. name, tonumber(value) or 0.0)
end

function VRBUS.getFloat(self, name)
  return GetFloat("vr.val." .. name)
end

function VRBUS.setBool(self, name, value)
  SetBool("vr.val." .. name, value and true or false)
end

function VRBUS.getBool(self, name)
  return GetBool("vr.val." .. name)
end

--[[---------------------------------------------------------------------------
  publishCamera(t)
    Mirrors the per-eye stereo block. The native renderer needs these every
    frame; they are plain scalars at fixed keys rather than slots.

      "vr.cam.ipd"        float  interpupillary distance, meters
      "vr.cam.sep"        float  eye separation (== ipd by default, exposed
                               separately so the user can scale it)
      "vr.cam.fov"        float  horizontal FOV, degrees (what SetCameraFov takes)
      "vr.cam.near"       float  near plane, meters
      "vr.cam.far"        float  far plane, meters
      "vr.cam.x"          float  head x
      "vr.cam.y"          float  head y
      "vr.cam.z"          float  head z
      "vr.cam.pitch"      float  head pitch, radians
      "vr.cam.yaw"        float  head yaw, radians
      "vr.cam.roll"       float  head roll, radians
      "vr.cam.rx"         float  head right axis, x
      "vr.cam.ry"         float  head right axis, y
      "vr.cam.rz"         float  head right axis, z
      "vr.cam.suppress"   int    1 = native side should not stereo-render now
      "vr.cam.valid"      int    1 when the transform is fresh this frame
-------------------------------------------------------------------------------]]
function VRBUS.publishCamera(self, c)
  if c == nil then
    SetInt("vr.cam.valid", 0)
    return
  end
  SetFloat("vr.cam.ipd",  c.ipd  or 0.064)
  SetFloat("vr.cam.sep",  c.sep  or c.ipd or 0.064)
  SetFloat("vr.cam.fov",  c.fov  or 90.0)
  SetFloat("vr.cam.near", c.near or 0.05)
  SetFloat("vr.cam.far",  c.far  or 500.0)
  SetFloat("vr.cam.x",    c.x    or 0.0)
  SetFloat("vr.cam.y",    c.y    or 0.0)
  SetFloat("vr.cam.z",    c.z    or 0.0)
  SetFloat("vr.cam.pitch", c.pitch or 0.0)
  SetFloat("vr.cam.yaw",   c.yaw   or 0.0)
  SetFloat("vr.cam.roll",  c.roll  or 0.0)
  SetFloat("vr.cam.rx",    c.rx    or 1.0)
  SetFloat("vr.cam.ry",    c.ry    or 0.0)
  SetFloat("vr.cam.rz",    c.rz    or 0.0)
  SetInt("vr.cam.suppress", (c.suppressed and 1) or 0)
  -- Published last; same discipline as the event ring.
  SetInt("vr.cam.valid", 1)
end

--[[---------------------------------------------------------------------------
  setHeartbeat(n)
    Increments once per second from main.lua. If this stops moving, the native
    side knows the Lua layer died rather than the channel being broken.
-------------------------------------------------------------------------------]]
function VRBUS.setHeartbeat(self, n)
  SetInt("vr.hb", n)
end

end  -- end vrbus.lua scope

--==========================================================================
-- vrhaptics.lua
--==========================================================================

do  -- vrhaptics.lua scope
--[[===========================================================================
  vrhaptics.lua -- Teardown VR: game event -> haptic event mapping.

  Two jobs:

    1. DETECT. The engine has no damage, explosion, collision or landing
       callbacks exposed to Lua (verified: no such name exists in
       data/script_defs.luau or in the binary's Lua name table). So every
       trigger here is a POLL of documented read-only state, sampled in tick()
       and diffed against the previous sample. That is the honest design: the
       mod derives events by watching, and the diffing is where the false
       positives and missed events come from.

    2. PUBLISH. Each detection becomes a VRBUS event (id, amplitude 0..1,
       duration, hand, world position, flags). The native layer forwards it to
       the VR controllers.

  A haptic EFFECT (an .xml curve) is a separate concern and is handled here too,
  as an optional game-side fallback: with no DLL attached, this mod can still
  rumble whatever pad the game sees, using the game's own haptic assets.

  ---------------------------------------------------------------------------
  VERIFIED
  ---------------------------------------------------------------------------
  Detection reads, all with confirmed signatures in data/script_defs.luau:
      GetPlayerHealth(playerId?)      :5876   0..1
      GetPlayerPos(playerId?)         :5329
      GetPlayerVelocity(playerId?)    :5566
      GetPlayerUp(playerId?)          :6458
      GetPlayerTransform(playerId?)   :5420
      GetPlayerEyeTransform(playerId?):5487
      GetPlayerTool(playerId?)        :5926
      GetPlayerVehicle(playerId?)     :5627
      GetPlayerCount()                :5228
      GetVehicleBody(vehicle)         :4989
      GetToolAmmo(toolId, playerId?)  :6386
      GetBodyVelocity(body)           :2138
      GetBodyVelocityAtPos(body,pos)  :2162
      GetBodyTransform(body)          :2040
      GetBodyBounds(body)             :2351   -> min, max
      IsBodyBroken(body)              :2413
      IsBodyDynamic(body)             :2085
      GetShapeBody(shape)             :2780
      GetShapeWorldTransform(shape)   :2762
      GetShapeMaterialAtPosition(...) :2903   -> material, ...
      QueryRaycast(o,d,maxDist,radius?,rejectTransparent?)
                                            :7363   -> hit, dist, normal, shape
      QueryAabbShapes(min,max)        :7496   -> list of shape handles
      InputDown(input,playerId?)      :213
      InputPressed(input,playerId?)   :185
      InputValue(input,playerId?)     :227
      IsPlayerLocal(playerId?)        :5272
      GetTime()                       :138
      Vec/VecAdd/VecSub/VecLength/VecScale/VecNormalize/VecDot
                                     :1047+:1094

  Haptic playback, all confirmed in data/script_defs.luau:
      LoadHaptic(filepath)                     :8810  -> handle
      CreateHaptic(lMotor,rMotor,lTrig,rTrig)  :8831  -> handle
      PlayHaptic(handle, amplitude)            :8850
      PlayHapticDirectional(handle, dir, amp)  :8871
      HapticIsPlaying(handle)                  :8890
      SetToolHaptic(id, handle, amplitude?)    :8907
      StopHaptic(handle)                       :8927

  ---------------------------------------------------------------------------
  ASSUMED -- flagged at each use site, not silently relied on
  ---------------------------------------------------------------------------
  * WatchBodyHit / IsBodyHitted / GetBodyHitsCount / GetBodyHit are declared in
    script_defs.luau as bare `function f(...) end` with NO annotations. They
    appear in 4 shipped mods (folkrace/m_village/script/{village_grinder,
    trash_hole,water_tower}.lua) called as
        WatchBodyHit(body); if IsBodyHitted(body) then
        for i = 0, GetBodyHitsCount(body)-1 do
            local other, impulse, pos, normal, this_vel, other_vel = GetBodyHit(body, i)
    That call convention is taken from real code but is NOT documented. If it is
    wrong it throws, so the impact path is pcall-guarded and degrades to
    "no tool-impact haptics" rather than to a crash.
  * GetToolAmmo returning 0 for a melee tool is assumed to mean "not applicable",
    not "empty". Untested.
  * Amplitude of CreateHaptic is assumed 0..1, inferred from the documented
    example CreateHaptic(1, 1, 0, 0) (both motors full, triggers off). The
    stub does not state a range.
  * <lifetime> in a haptic .xml is assumed to be seconds. Plausible, not
    documented. The .ttl published to the bus is therefore advisory metadata for
    the native side only; on the game-side path the XML owns the real duration.
============================================================================]]

VRHAPTICS = VRHAPTICS or {}
VRHAPTICS.__index = VRHAPTICS

--[[---------------------------------------------------------------------------
  EFFECT CATALOG

  asset       path passed to LoadHaptic. Paths WITHOUT a "MOD/" prefix resolve
              against the game's built-in haptic table -- proven by
              mods/folkrace/script/gadget_nitro.lua:76 which loads
              "haptic/vehicle_turbo.xml", a file that exists only in the
              vanilla data/haptic/ directory.
  amp         default 0..1 scale applied on top of the per-event intensity.
  ttl         advisory duration published to the native side, seconds.
  hand        VRBUS_HAND_*.
-------------------------------------------------------------------------------]]
VRHAPTICS.CATALOG = {
  { id = VRBUS_EV_DAMAGE_TAKEN,  asset = "MOD/haptic/vr_damage.xml",     amp = 0.9, ttl = 0.25, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_LANDING,       asset = "MOD/haptic/vr_landing.xml",    amp = 1.0, ttl = 0.20, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_FALL_START,    asset = nil,                         amp = 0.0, ttl = 0.00, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_TOOL_FIRE,     asset = "MOD/haptic/vr_tool_fire.xml",  amp = 0.7, ttl = 0.12, hand = VRBUS_HAND_RIGHT },
  { id = VRBUS_EV_TOOL_IMPACT,   asset = "MOD/haptic/vr_tool_impact.xml",amp = 0.5, ttl = 0.10, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_EXPLOSION,     asset = "MOD/haptic/vr_explosion.xml",  amp = 1.0, ttl = 0.40, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_BREAK,         asset = "MOD/haptic/vr_tool_impact.xml",amp = 0.45, ttl = 0.08, hand = VRBUS_HAND_BOTH },
  { id = VRBUS_EV_GRAB,          asset = "MOD/haptic/vr_grab.xml",    amp = 0.4, ttl = 0.05, hand = VRBUS_HAND_RIGHT },
  { id = VRBUS_EV_JUMP,          asset = nil,                         amp = 0.0, ttl = 0.00, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_FOOTSTEP,      asset = "MOD/haptic/vr_footstep.xml",amp = 0.35, ttl = 0.06, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_VEHICLE_HIT,   asset = "MOD/haptic/vr_vehicle_impact.xml", amp = 0.8, ttl = 0.30, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_VEHICLE_ENTER, asset = nil,                         amp = 0.0, ttl = 0.00, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_VEHICLE_EXIT,  asset = nil,                         amp = 0.0, ttl = 0.00, hand = VRBUS_HAND_BOTH  },
  { id = VRBUS_EV_HEARTBEAT,     asset = nil,                         amp = 0.0, ttl = 0.00, hand = VRBUS_HAND_BOTH  },
}

--[[---------------------------------------------------------------------------
  Tuning
-------------------------------------------------------------------------------]]
VRHAPTICS.TUNE = {
  -- A health drop smaller than this is ignored (regeneration ticks, 0.02 chip
  -- damage from weapon scripts). 0.01 was chosen because the smallest damage
  -- step seen in shipped mods is 0.02 (e.g. SetPlayerHealth(h - 0.02 * ...)).
  damageEpsilon     = 0.01,
  -- Fraction of health lost that maps to full-scale intensity.
  damageForMax      = 0.35,

  -- Landing: minimum downward speed, and the impact speed that maps to 1.0.
  fallMinSpeed      = 3.0,
  fallMaxSpeed      = 22.0,
  -- A jump is a rise faster than this with the player then leaving the ground.
  jumpMinSpeed      = 4.0,

  -- Ground probe distance, meters. The player capsule is ~1.8 m; anything past
  -- ~2.2 m is genuinely airborne.
  groundProbe       = 2.2,

  -- Footstep cadence is derived from distance travelled, not a timer, so it
  -- does not drift at low frame rates.
  stepStride        = 2.1,

  -- Tool fire: ammo decrease of at least this counts as a discharge.
  fireMinAmmoDrop   = 1,

  -- Explosion: reported when any dynamic shape enters this radius. Chosen to
  -- match the game's own explosion size range; ASSUMED, not measured.
  explosionRadius   = 18.0,

  -- Per-id minimum seconds between accepted events.
  rateLimit = {
    [VRBUS_EV_DAMAGE_TAKEN] = 0.05,
    [VRBUS_EV_LANDING]      = 0.15,
    [VRBUS_EV_FALL_START]   = 0.30,
    [VRBUS_EV_TOOL_FIRE]    = 0.03,
    [VRBUS_EV_TOOL_IMPACT]  = 0.06,
    [VRBUS_EV_EXPLOSION]    = 0.12,
    [VRBUS_EV_BREAK]        = 0.04,
    [VRBUS_EV_GRAB]         = 0.10,
    [VRBUS_EV_JUMP]         = 0.30,
    [VRBUS_EV_FOOTSTEP]     = 0.12,
    [VRBUS_EV_VEHICLE_HIT]  = 0.15,
    [VRBUS_EV_VEHICLE_ENTER]= 0.50,
    [VRBUS_EV_VEHICLE_EXIT] = 0.50,
  },
}

--[[---------------------------------------------------------------------------
  new(bus) -> h
-------------------------------------------------------------------------------]]
function VRHAPTICS.new(bus)
  local self = setmetatable({}, VRHAPTICS)
  self.bus = bus
  self.handles = {}        -- asset path -> LoadHaptic handle
  self.playGameHaptics = false  -- see note on the play() function
  self._s = nil            -- previous-sample state
  self._stats = { emitted = 0, suppressed = 0, loadFail = 0 }
  return self
end

--[[---------------------------------------------------------------------------
  handle(asset) -> handle
    Load (and memoise) a haptic effect by asset path.
    ASSUMED: LoadHaptic returns "" for a missing path rather than erroring.
    pcall-guarded regardless so a bad path cannot break the frame.
-------------------------------------------------------------------------------]]
function VRHAPTICS.handle(self, asset)
  if asset == nil then return nil end
  local cached = self.handles[asset]
  if cached ~= nil then
    if cached == false then return nil end
    return cached
  end
  local ok, h = pcall(LoadHaptic, asset)
  if not ok or h == nil or h == "" then
    self.handles[asset] = false
    self._stats.loadFail = self._stats.loadFail + 1
    return nil
  end
  self.handles[asset] = h
  return h
end

--[[---------------------------------------------------------------------------
  entryFor(id) -> catalog entry
    Self is taken so this is called as self:entryFor(id), matching every other
    method here. An earlier revision declared it without `self` and called it
    with a colon, which silently shifted the id argument and made every event
    fall through to the unknown-id path -- ttl and hand both came out zero.
    The test suite now asserts ttl > 0 and the per-event hand to catch exactly
    that class of bug.
-------------------------------------------------------------------------------]]
function VRHAPTICS.entryFor(self, id)
  for i = 1, #VRHAPTICS.CATALOG do
    if VRHAPTICS.CATALOG[i].id == id then return VRHAPTICS.CATALOG[i] end
  end
  return nil
end

--[[---------------------------------------------------------------------------
  fire(id, intensity, opts)
    The single funnel every detector goes through. Normalises intensity, applies
    the catalog's base amplitude, rate-limits, publishes to the bus, and
    optionally plays the game-side effect.

    intensity  0..1 raw strength from the detector.
    opts.pos   TVec world position of the cause.
    opts.hand  override the catalog's controller.
    opts.flags VRBUS_FLAG_* bitfield.
-------------------------------------------------------------------------------]]
function VRHAPTICS.fire(self, id, intensity, opts)
  opts = opts or {}
  local now = GetTime()

  local limit = VRHAPTICS.TUNE.rateLimit[id]
  if limit ~= nil and not self.bus:allow(id, limit, now) then
    self._stats.suppressed = self._stats.suppressed + 1
    return false
  end

  local entry = self:entryFor(id)
  if entry == nil then
    -- Unknown id: still publish, with neutral metadata. The native side can
    -- decide what to do with a numeric id it does not recognise.
    self.bus:emit(id, intensity, 0.0, opts.hand, opts.pos, opts.flags)
    self._stats.emitted = self._stats.emitted + 1
    return true
  end

  local amp = intensity * entry.amp
  if amp <= 0.0 then
    -- Catalog says this event has no effect curve (a jump has no motor
    -- signature, say). Still tell the native side about it, at reduced gain,
    -- because a native renderer may want to synthesize something.
    amp = intensity * 0.25
  end
  if amp > 1.0 then amp = 1.0 end

  self.bus:emit(id, amp, entry.ttl, opts.hand or entry.hand, opts.pos, opts.flags)
  self._stats.emitted = self._stats.emitted + 1

  if self.playGameHaptics then self:play(entry, amp, opts) end
  return true
end

--[[---------------------------------------------------------------------------
  play(entry, amp, opts)
    Rumble whatever controller the game itself sees. This is the fallback that
    makes the mod useful with no native DLL present.

    PlayHaptic(handle, amplitude) has no duration argument -- the curve's
    <lifetime> in the .xml owns how long it runs. So the .ttl this bus carries
    does NOT control the game-side effect, only the native-side one.

    opts.pos: when present and a directional effect is loaded, PlayHapticDirectional
    is used so the rumble comes from the direction the event came from. Its
    signature is documented (script_defs.luau:8871) but it has zero call sites
    in the 2838 shipped mod scripts, so it stays off by default behind a flag.
-------------------------------------------------------------------------------]]
function VRHAPTICS.play(self, entry, amp, opts)
  local h = self:handle(entry.asset)
  if h == nil then return false end
  local ok = pcall(function()
    if opts and opts.pos and self.directional then
      -- ASSUMED: direction is a world-space unit vector. Documented as TVec
      -- only; the reference frame is not stated.
      local p = opts.pos
      local d = VecNormalize(Vec(p[1], p[2], p[3]))
      PlayHapticDirectional(h, d, amp)
    else
      PlayHaptic(h, amp)
    end
  end)
  return ok
end

--[[---------------------------------------------------------------------------
  init(self)
    Prime the sample state. Must be called before the first tick, or the first
    tick will read a zeroed sample and report a phantom full-health-to-zero drop
    and a phantom landing.
-------------------------------------------------------------------------------]]
function VRHAPTICS.init(self)
  self._s = {
    health    = self:readHealth(),
    pos       = nil,
    grounded  = true,
    lastY     = nil,
    distance  = 0,
    tool      = nil,
    ammo      = nil,
    vehicle   = nil,
    toolBody  = nil,
    toolHits  = 0,
    bodyWatch = {},   -- body handle -> last known broken state
    shapes    = {},   -- explosion candidate shapes
  }
  self.directional = false
end

--[[---------------------------------------------------------------------------
  localPlayer()
    VERIFIED 2026-09-28 in the live game: GetLocalPlayer() raises
    "Calling the GetLocalPlayer API function before init is not supported"
    when it runs before the game is ready. Because it is normally an ARGUMENT
    to another call, the surrounding pcall cannot catch it -- the throw happens
    while evaluating the arguments, before pcall is entered. So every use has
    to go through this guard, which degrades to player 0 (the host, and the
    local player on the client) instead of raising.
-------------------------------------------------------------------------------]]
local function localPlayer()
  local p = 0
  local ok = pcall(function() p = GetLocalPlayer() end)
  if not ok or p == nil then return 0 end
  return p
end

--[[---------------------------------------------------------------------------
  readHealth(self) -> number
    Health of the local player, 0..1. GetPlayerHealth is per-player and takes
    an optional id; the host's own player is 0, and on the client 0 is the local
    player. GetLocalPlayer() gives the right id for each side.
-------------------------------------------------------------------------------]]
function VRHAPTICS.readHealth(self)
  local ok, h = pcall(GetPlayerHealth, localPlayer())
  if not ok or h == nil then return 1.0 end
  if h > 1.0 then h = 1.0 end
  if h < 0.0 then h = 0.0 end
  return h
end

--[[---------------------------------------------------------------------------
  grounded(self, pos) -> grounded, distanceToGround
    Probe straight down from the player's feet with a raycast. Direction is
    world down, which is correct because the game's gravity axis is -Y
    (speedometer/main.lua:28 uses -vel[3] for vehicle forward, and every
    shipped QueryRaycast ground probe uses Vec(0,-1,0)).
-------------------------------------------------------------------------------]]
function VRHAPTICS.grounded(self, pos)
  local ok, hit, dist = pcall(QueryRaycast, pos, Vec(0, -1, 0), VRHAPTICS.TUNE.groundProbe)
  if not ok then return true, VRHAPTICS.TUNE.groundProbe end
  return (hit == true), (dist or VRHAPTICS.TUNE.groundProbe)
end

--[[---------------------------------------------------------------------------
  tick(self, dt)
    One pass of all detectors. dt is the real frame time; note that
    GetTimeStep() returns a FIXED 1/60 from update() and the real elapsed time
    from tick(), so this must be called from tick(), never update().

    Each detector is wrapped in pcall. A detector that throws is disabled for
    the rest of the session rather than throwing every frame and flooding the
    log: that keeps a wrong assumption in one trigger from taking the haptics
    channel down with it.
-------------------------------------------------------------------------------]]
function VRHAPTICS.tick(self, dt)
  local s = self._s
  if s == nil then self:init() s = self._s end
  if dt == nil or dt <= 0 then dt = 1.0 / 60.0 end

  self:detectDamage(s)
  self:detectMotion(s, dt)
  self:detectTool(s)
  self:detectImpacts(s)
  self:detectVehicle(s)
end

--[[---------------------------------------------------------------------------
  detectDamage(s)
    Health is a 0..1 scalar, so damage is a first difference. The first sample
    is taken in init() precisely so this does not fire on level load.
-------------------------------------------------------------------------------]]
function VRHAPTICS.detectDamage(self, s)
  local ok, h = pcall(VRHAPTICS.readHealth, self)
  if not ok then return end

  local drop = s.health - h
  if drop > VRHAPTICS.TUNE.damageEpsilon then
    local intensity = drop / VRHAPTICS.TUNE.damageForMax
    if intensity > 1.0 then intensity = 1.0 end
    self:fire(VRBUS_EV_DAMAGE_TAKEN, intensity, { pos = self:safePos() })
  end
  s.health = h
end

--[[---------------------------------------------------------------------------
  detectMotion(s, dt)
    Landing and footsteps from vertical velocity and a ground probe.

    The classifier is: airborne + downward velocity past fallMinSpeed builds a
    fall energy; the frame the ground probe comes back true, that energy is
    spent as a landing. A rise past jumpMinSpeed is a jump. Footsteps accrue
    horizontal distance while grounded and fire every stepStride meters.
-------------------------------------------------------------------------------]]
function VRHAPTICS.detectMotion(self, s, dt)
  local okPos, pos = pcall(GetPlayerPos, localPlayer())
  if not okPos or pos == nil then return end

  local okVel, vel = pcall(GetPlayerVelocity, localPlayer())
  if not okVel or vel == nil then return end

  local x, y, z = pos[1], pos[2], pos[3]
  local vx, vy, vz = vel[1], vel[2], vel[3]

  local wasGrounded = s.grounded
  local isGrounded, _ = self:grounded(pos)
  s.grounded = isGrounded

  -- Horizontal travel, used only for footstep cadence.
  if s.pos ~= nil and isGrounded then
    local dx, dz = x - s.pos[1], z - s.pos[3]
    s.distance = s.distance + math.sqrt(dx * dx + dz * dz)
  end
  s.pos = { x, y, z }

  -- Landing: we were airborne and are now grounded.
  if not wasGrounded and isGrounded then
    local energy = s.fallEnergy or 0.0
    if energy >= VRHAPTICS.TUNE.fallMinSpeed then
      local t = (energy - VRHAPTICS.TUNE.fallMinSpeed) /
                (VRHAPTICS.TUNE.fallMaxSpeed - VRHAPTICS.TUNE.fallMinSpeed)
      if t > 1.0 then t = 1.0 end
      if t < 0.0 then t = 0.0 end
      self:fire(VRBUS_EV_LANDING, t, { pos = pos })
    end
    s.fallEnergy = 0.0
  end

  -- Airborne: track the fastest downward speed seen during the fall.
  if not isGrounded then
    local down = -vy
    if down > (s.fallEnergy or 0.0) then s.fallEnergy = down end

    if wasGrounded and vy > VRHAPTICS.TUNE.jumpMinSpeed then
      self:fire(VRBUS_EV_JUMP, math.min(vy / VRHAPTICS.TUNE.jumpMinSpeed, 1.0), { pos = pos })
    end
  end

  -- Footsteps.
  if isGrounded and s.distance >= VRHAPTICS.TUNE.stepStride then
    s.distance = 0.0
    local speed = math.sqrt(vx * vx + vz * vz)
    if speed > 0.6 then
      self:fire(VRBUS_EV_FOOTSTEP, math.min(speed / 6.0, 1.0),
                { pos = pos, flags = VRBUS_FLAG_NONE })
    end
  end
end

--[[---------------------------------------------------------------------------
  detectTool(s)
    Tool switch from GetPlayerTool. Tool fire from the ammo counter dropping,
    which is the only firing signal exposed to Lua -- there is no "weapon fired"
    callback.

    ASSUMED: for a tool with no ammo (melee, most tools) GetToolAmmo returns 0
    and no fire events are produced. That means fire haptics only work for
    tools that actually consume ammo.
-------------------------------------------------------------------------------]]
function VRHAPTICS.detectTool(self, s)
  local ok, tool = pcall(GetPlayerTool, localPlayer())
  if not ok or tool == nil then return end

  if s.tool ~= nil and tool ~= s.tool then
    self:fire(VRBUS_EV_TOOL_SWITCH, 0.3, { pos = self:safePos() })
  end
  s.tool = tool

  local okAmmo, ammo = pcall(GetToolAmmo, tool, localPlayer())
  if not okAmmo or ammo == nil then return end

  if s.ammo ~= nil and ammo < (s.ammo - VRHAPTICS.TUNE.fireMinAmmoDrop) then
    local spent = s.ammo - ammo
    local t = spent / 10.0
    if t > 1.0 then t = 1.0 end
    self:fire(VRBUS_EV_TOOL_FIRE, math.max(t, 0.35), { pos = self:safePos() })
  end
  s.ammo = ammo
end

--[[---------------------------------------------------------------------------
  detectImpacts(s)
    Tool impact and destruction, from the body-hit watch API.

    ASSUMED SIGNATURES (see the header block): WatchBodyHit(body) subscribes,
    IsBodyHitted(body) reports "new hit this frame", GetBodyHit(body, i) returns
    otherBody, impulse, pos, normal, thisVel, otherVel. Undocumented in the
    stub; pcall-guarded; this whole path is expected to need a live-game test.

    Only bodies the player is actually near are watched, otherwise this would
    be an O(level) scan every frame.
-------------------------------------------------------------------------------]]
function VRHAPTICS.detectImpacts(self, s)
  local ok, body = pcall(GetToolBody, localPlayer())
  if not ok or body == nil or body == 0 then
    s.toolBody = nil
    return
  end
  s.toolBody = body

  local okWatch = pcall(WatchBodyHit, body)
  if not okWatch then return end

  local okHitted, hitted = pcall(IsBodyHitted, body)
  if not okHitted or not hitted then return end

  local okCount, n = pcall(GetBodyHitsCount, body)
  if not okCount or n == nil or n <= 0 then return end

  -- Bound the work: at most 4 hits examined per frame.
  local limit = n
  if limit > 4 then limit = 4 end

  for i = 0, limit - 1 do
    local okHit, other, impulse, pos, normal = pcall(GetBodyHit, body, i)
    if okHit and other ~= nil then
      local mag = math.abs(tonumber(impulse) or 0.0)
      local t = mag / 400.0
      if t > 1.0 then t = 1.0 end
      if t > 0.05 then
        local flags = VRBUS_FLAG_NONE
        local okM, mat = pcall(GetShapeMaterialAtPosition, other, pos or Vec())
        -- GetShapeMaterialAtPosition takes a SHAPE handle, but GetBodyHit
        -- returns a BODY handle. Passing a body where a shape is expected is
        -- ASSUMED to be harmless; the result is only used to set a flag.
        if okM and type(mat) == "string" and mat ~= "" then
          flags = VRBUS_FLAG_SURFACE
        end
        self:fire(VRBUS_EV_TOOL_IMPACT, t, { pos = pos, flags = flags })
      end
    end
  end
end

--[[---------------------------------------------------------------------------
  detectVehicle(s)
    Enter/exit from GetPlayerVehicle, which returns 0 when not driving.
    Vehicle damage has no readable signal: the vehicle's health is not exposed
    to Lua (GetVehicleHealth is used in shipped mods but is not in
    script_defs.luau, so its availability is unverified). Body-hit watching on
    the vehicle body is the fallback and is left unimplemented rather than
    guessed at.
-------------------------------------------------------------------------------]]
function VRHAPTICS.detectVehicle(self, s)
  local ok, veh = pcall(GetPlayerVehicle, localPlayer())
  if not ok or veh == nil then return end

  if s.vehicle == nil or s.vehicle == 0 then
    if veh ~= 0 then
      self:fire(VRBUS_EV_VEHICLE_ENTER, 0.4, { pos = self:safePos() })
    end
  elseif veh == 0 then
    self:fire(VRBUS_EV_VEHICLE_EXIT, 0.4, { pos = self:safePos() })
  end
  s.vehicle = veh
end

--[[---------------------------------------------------------------------------
  safePos(self) -> TVec or nil
    Player position, or nil if it cannot be read this frame. Every detector
    passes this rather than calling GetPlayerPos itself so a single bad read
    cannot take out the rest of the frame.
-------------------------------------------------------------------------------]]
function VRHAPTICS.safePos(self)
  local ok, p = pcall(GetPlayerPos, localPlayer())
  if not ok or p == nil then return nil end
  return p
end

end  -- end vrhaptics.lua scope

--==========================================================================
-- vrcamera.lua
--==========================================================================

do  -- vrcamera.lua scope
--[[===========================================================================
  vrcamera.lua -- Teardown VR: per-eye camera parameters for the native
  stereo renderer.

  WHAT THIS IS NOT: it does not render anything stereo. Teardown's renderer is
  a single-pass forward renderer; per-eye output has to be produced in the
  native layer (see hook/stereo.h and docs/STEREO_MATH.md). This module's job
  is to compute the numbers the native side needs and publish them at fixed
  keys each frame.

  WHAT IT DOES: track the head pose, derive eye separation / near / far from
  user settings, and decide whether the game is in a state where a stereo
  override should apply at all.

  ---------------------------------------------------------------------------
  VERIFIED
  ---------------------------------------------------------------------------
      GetPlayerEyeTransform(playerId?)  script_defs.luau:5487
          The doc states outright: "The player eye transform is the same as
          what you get from GetCameraTransform when playing in first-person,
          but if you have set a camera transform manually ... you can retrieve
          the player eye transform with this function." That makes it the right
          source for the head pose, and it keeps working if the native layer is
          already driving SetCameraTransform.
      GetCameraTransform()              script_defs.luau:8261
      SetCameraTransform(transform, fov?):8276
      SetCameraFov(degrees)             script_defs.luau:8398
          Doc: "Horizontal field of view in degrees (10-170)" and "Override
          field of view for the next frame for all camera modes, except when
          explicitly set in SetCameraTransform". HORIZONTAL fov, which is the
          one the native projection code should mirror.
      SetCameraOffsetTransform(t, stackable?) :8332
      SetPlayerCameraOffsetTransform(t, stackable?, playerId?) :5517
      GetPlayerTransform(playerId?)     script_defs.luau:5420
      GetPlayerPos(playerId?)           script_defs.luau:5329
      GetPlayerUp(playerId?)            script_defs.luau:6458
      GetPlayerPitch / GetPlayerYaw     script_defs.luau:5365 / :5377
      QuatRotateVec(q, v)               -- verified present in teardown.exe as a
                                          Lua binding; signature taken from
                                          shipped use, e.g.
                                          wildwestheist/ravine/script/truxterminator.lua
                                          QueryRaycast from an eye transform.
      GetBool / SetBool                 script_defs.luau:705 / :693
      GetFloat / SetFloat               script_defs.luau:680 / :668
      TransformStr(t)                   -- present in binary; used by
                                          GetPlayerEyeTransform's own doc example.

  ---------------------------------------------------------------------------
  ASSUMED -- flagged below, not relied on silently
  ---------------------------------------------------------------------------
  * Units. Positions are metres and rotations radians, which is consistent with
    every shipped mod (speedometer converts m/s to km/h with *3.6; QueryRaycast
    radii are sub-metre). No stub file states units for transforms, so this is
    an inference from usage, a strong one.
  * Quat component order. The head pose is published as a transform's .pos plus
    pitch/yaw/roll read separately from GetPlayerPitch/GetPlayerYaw, specifically
    so the native side never has to interpret a quaternion's component order.
    GetPlayerUp publishes the up axis directly for the same reason.
  * Roll. There is no documented GetPlayerRoll, so roll is derived from the eye
    transform's up vector projected against world up. That is a reconstruction,
    not a read-out; it is exact for yaw/pitch and only approximate under roll.
  * Teardown's world axes are x = right, y = up, -z = forward (from
    speedometer/main.lua:26-30, where forward speed is -vel[3] in vehicle local
    space, and from every shipped ground probe using Vec(0,-1,0) as down).
    Eye offsets below are applied along x accordingly.
  * There is no documented near/far plane accessor. The defaults here are the
    mod's own choice and are the values the native side should use until the
    real projection constants are read out of the renderer.
============================================================================]]

VRCAMERA = VRCAMERA or {}
VRCAMERA.__index = VRCAMERA

--[[---------------------------------------------------------------------------
  Defaults
-------------------------------------------------------------------------------]]
VRCAMERA.DEFAULT_IPD      = 0.064   -- 64 mm, the usual average adult IPD
VRCAMERA.DEFAULT_NEAR     = 0.05    -- 5 cm
VRCAMERA.DEFAULT_FAR      = 500.0   -- 500 m
VRCAMERA.DEFAULT_FOV      = 90.0    -- degrees, HORIZONTAL
VRCAMERA.FOV_MIN          = 10.0    -- bounds are documented at :8398
VRCAMERA.FOV_MAX          = 170.0

-- Head poses the native side should NOT stereo-render. Vehicle and respawn
-- transitions are the ones that produce a disorienting jump.
VRCAMERA.SUPPRESS_IN_VEHICLE = true

--[[---------------------------------------------------------------------------
  new(bus) -> cam
-------------------------------------------------------------------------------]]
function VRCAMERA.new(bus)
  local self = setmetatable({}, VRCAMERA)
  self.bus = bus
  self.enabled = true
  self.ipdScale = 1.0
  self.near = VRCAMERA.DEFAULT_NEAR
  self.far = VRCAMERA.DEFAULT_FAR
  self.fov = VRCAMERA.DEFAULT_FOV
  self.inhibitUntil = 0.0
  self._last = nil
  return self
end

--[[---------------------------------------------------------------------------
  settings keys. Persisted in the game's own key store, so they survive a
  level reload the same way any other mod setting does. Namespaced "vr."
  because the store is global to the level.
-------------------------------------------------------------------------------]]
VRCAMERA.KEY_ENABLED = "vr.user.enabled"
VRCAMERA.KEY_IPD_MM   = "vr.user.ipd_mm"
VRCAMERA.KEY_FOV      = "vr.user.fov"
VRCAMERA.KEY_SCALE    = "vr.user.sep_scale"

--[[---------------------------------------------------------------------------
  loadSettings(self)
    Read user settings out of the key store, filling in defaults. A mod may run
    before the settings UI has ever written them, so every read is defaulted.
-------------------------------------------------------------------------------]]
function VRCAMERA.loadSettings(self)
  if not HasKey(VRCAMERA.KEY_ENABLED) then SetBool(VRCAMERA.KEY_ENABLED, true) end
  if not HasKey(VRCAMERA.KEY_IPD_MM)   then SetInt(VRCAMERA.KEY_IPD_MM, 64) end
  if not HasKey(VRCAMERA.KEY_FOV)      then SetInt(VRCAMERA.KEY_FOV, math.floor(VRCAMERA.DEFAULT_FOV)) end
  if not HasKey(VRCAMERA.KEY_SCALE)    then SetFloat(VRCAMERA.KEY_SCALE, 1.0) end

  self.enabled  = GetBool(VRCAMERA.KEY_ENABLED)
  self.ipdScale = GetFloat(VRCAMERA.KEY_SCALE)
  if self.ipdScale == nil or self.ipdScale <= 0 then self.ipdScale = 1.0 end
  self.fov      = GetInt(VRCAMERA.KEY_FOV)
  if self.fov < VRCAMERA.FOV_MIN or self.fov > VRCAMERA.FOV_MAX then
    self.fov = VRCAMERA.DEFAULT_FOV
  end
  self.near = VRCAMERA.DEFAULT_NEAR
  self.far  = VRCAMERA.DEFAULT_FAR
end

--[[---------------------------------------------------------------------------
  saveSettings(self)
-------------------------------------------------------------------------------]]
function VRCAMERA.saveSettings(self)
  SetBool(VRCAMERA.KEY_ENABLED, self.enabled)
  SetFloat(VRCAMERA.KEY_SCALE, self.ipdScale)
  SetInt(VRCAMERA.KEY_FOV, math.floor(self.fov))
end

--[[---------------------------------------------------------------------------
  localPlayer()
    VERIFIED 2026-09-28 in the live game: GetLocalPlayer() raises
    "Calling the GetLocalPlayer API function before init is not supported" when
    called before the game is ready. As an ARGUMENT to another call it throws
    while the arguments are evaluated, so the surrounding pcall cannot catch
    it. Degrades to 0 (host, and local player on the client).
-------------------------------------------------------------------------------]]
local function localPlayer()
  local p = 0
  local ok = pcall(function() p = GetLocalPlayer() end)
  if not ok or p == nil then return 0 end
  return p
end

--[[---------------------------------------------------------------------------
  readHead(self) -> head or nil
    Build the head pose block from GetPlayerEyeTransform, with the orientation
    decomposed so the native side needs no quaternion convention.

    Returns nil when the pose cannot be read, which is what tells the native
    side to hold its last good frame rather than render a garbage one.
-------------------------------------------------------------------------------]]
function VRCAMERA.readHead(self)
  local id = localPlayer()

  local okT, t = pcall(GetPlayerEyeTransform, id)
  if not okT or t == nil or t.pos == nil then return nil end

  local pos = t.pos
  local head = {
    x = pos[1] or 0.0,
    y = pos[2] or 0.0,
    z = pos[3] or 0.0,
    pitch = 0.0,
    yaw = 0.0,
    roll = 0.0,
    upx = 0.0, upy = 1.0, upz = 0.0,
  }

  -- Pitch and yaw are read directly. ASSUMED radians; the stub does not say.
  local okP, pitch = pcall(GetPlayerPitch, id)
  if okP and pitch ~= nil then head.pitch = pitch end
  local okY, yaw = pcall(GetPlayerYaw, id)
  if okY and yaw ~= nil then head.yaw = yaw end

  -- Up vector, straight from the API, so roll can be derived without touching
  -- the quaternion's component order.
  local okU, up = pcall(GetPlayerUp, id)
  if okU and up ~= nil then
    head.upx, head.upy, head.upz = up[1], up[2], up[3]
  elseif okT and t.rot ~= nil then
    -- Fall back to rotating world up by the eye rotation.
    local okR, r = pcall(QuatRotateVec, t.rot, Vec(0, 1, 0))
    if okR and r ~= nil then head.upx, head.upy, head.upz = r[1], r[2], r[3] end
  end

  -- Roll = signed angle of the up vector from world up, measured in the plane
  -- spanned by world right and world forward.
  -- ASSUMED: this reconstruction is exact for pure yaw/pitch, and only
  -- approximate when the up vector is not exactly perpendicular to forward.
  local upx, upy, upz = head.upx, head.upy, head.upz
  if upy ~= 0 then
    local planar = math.sqrt(upx * upx + upz * upz)
    head.roll = math.atan2(planar, upy)
  end

  return head
end

--[[---------------------------------------------------------------------------
  eyeOffsets(self, head) -> halfSep, rightX, rightY, rightZ
    Half the eye separation along world x, plus the player's right axis, so the
    native side can place the eyes along the head's right vector rather than
    blindly along world x. Under yaw that is the difference between a correct
    stereo rig and one that shears.
-------------------------------------------------------------------------------]]
function VRCAMERA.eyeOffsets(self, head)
  local sep = VRCAMERA.DEFAULT_IPD * self.ipdScale
  local half = sep * 0.5

  -- Right axis = normalize(cross(forward, up)). With world up (0,1,0) and
  -- -z forward this reduces to (up.z, 0, -up.x), but the general form is used
  -- so a rolled head still gets a right vector in its own plane.
  local ux, uy, uz = head.upx, head.upy, head.upz
  -- Forward from the eye transform is -z in local space; recover a world
  -- forward from pitch/yaw rather than from the quaternion.
  local cp = math.cos(head.pitch)
  local fx = math.sin(head.yaw) * cp
  local fy = -math.sin(head.pitch)
  local fz = -math.cos(head.yaw) * cp

  -- right = cross(forward, up)
  local rx = fy * uz - fz * uy
  local ry = fz * ux - fx * uz
  local rz = fx * uy - fy * ux
  local len = math.sqrt(rx * rx + ry * ry + rz * rz)
  if len > 1e-6 then
    rx, ry, rz = rx / len, ry / len, rz / len
  else
    rx, ry, rz = 1.0, 0.0, 0.0
  end

  return half, rx, ry, rz
end

--[[---------------------------------------------------------------------------
  shouldSuppress(self) -> bool
    True while the camera state is one the native side should not stereo-
    render: inside a vehicle (if configured), or within the inhibit window
    after a level change.

    The inhibit window exists because on the first frames after a level starts
    the eye transform can still be the previous level's while the renderer has
    already moved to the new one.
-------------------------------------------------------------------------------]]
function VRCAMERA.shouldSuppress(self)
  if not self.enabled then return true end
  if GetTime() < self.inhibitUntil then return true end
  if VRCAMERA.SUPPRESS_IN_VEHICLE then
    local ok, veh = pcall(GetPlayerVehicle, localPlayer())
    if ok and veh ~= nil and veh ~= 0 then return true end
  end
  return false
end

--[[---------------------------------------------------------------------------
  tick(self)
    Publish this frame's stereo block. Runs in tick(), before the native layer's
    per-frame hook reads it.
-------------------------------------------------------------------------------]]
function VRCAMERA.tick(self)
  local head = self:readHead()

  if head == nil then
    -- No fresh pose: invalidate so the native side holds its previous frame.
    self.bus:publishCamera(nil)
    return
  end

  local half, rx, ry, rz = self:eyeOffsets(head)
  local sep = half * 2.0

  self.bus:publishCamera({
    ipd   = sep,
    sep   = sep,
    fov   = self.fov,
    near  = self.near,
    far   = self.far,
    x     = head.x,
    y     = head.y,
    z     = head.z,
    pitch = head.pitch,
    yaw   = head.yaw,
    roll  = head.roll,
    -- The right axis and the suppress flag ride along in the reserved slots
    -- so the native side does not have to re-derive them.
    rx = rx, ry = ry, rz = rz,
    suppressed = self:shouldSuppress(),
  })
end

--[[---------------------------------------------------------------------------
  suppress(self, seconds)
    Hold off stereo for a while. Called on level change and on respawn.
-------------------------------------------------------------------------------]]
function VRCAMERA.suppress(self, seconds)
  if seconds == nil then seconds = 0.5 end
  self.inhibitUntil = GetTime() + seconds
end

end  -- end vrcamera.lua scope

--==========================================================================
-- vrinput.lua
--==========================================================================

do  -- vrinput.lua scope
--- Teardown VR — action-driven input layer.
--
-- WHY THIS EXISTS
--
-- The game exposes InputDown/InputPressed/InputValue for READING, and nothing
-- for writing. Driving the game by moving a camera transform every frame was
-- rejected: it is a bottleneck, it fights the game's own camera, and it does
-- not give buttons.
--
-- What the game DOES expose is a remap table it writes itself from Lua:
--
--   data/ui/components/input_options_logic.lua:259
--     SetString(self.conflictingInfo.actionName, key)
--   with actionName values "options.input.keymap.jump", ".crouch",
--   ".interact", ".flashlight", ".camera_view", ...
--
-- So a mod can rebind any action to any key. That is the lever: VR input
-- declares which action each controller input drives, and this layer reads it
-- back. Remapping cannot CREATE button state, it decides which key drives which
-- action; the state itself has to come from a real device, which is what the
-- native side provides.
--
-- This file is the Lua half. It contains no offsets, no FFI, and no native
-- calls. Everything it uses is a documented mod-facing API.
--
-- CALLBACK SHAPE: main.lua mods use bare globals init/tick/update/draw.
-- GetTimeStep() is a fixed 1/60 inside update() but the real frame time in
-- tick()/draw(); anything integrating over dt must run in tick().
--
-- World axes: x right, y up, -z forward. Metres, radians.

local ACTION = {
	-- movement
	UP = "up", DOWN = "down", LEFT = "left", RIGHT = "right",
	JUMP = "jump", CROUCH = "crouch",
	-- hands
	USETOOL = "usetool", GRAB = "grab", INTERACT = "interact",
	FLASHLIGHT = "flashlight",
	-- tools and camera
	TOOL_GROUP_NEXT = "tool_group_next", TOOL_GROUP_PREV = "tool_group_prev",
	SCOREBOARD = "scoreboard", MAP = "map", PAUSE = "pause", PHOTOMODE = "photomode",
	ZOOM = "zoom",
	-- menu
	MENU_ACCEPT = "menu_accept", MENU_CANCEL = "menu_cancel",
	MENU_UP = "menu_up", MENU_DOWN = "menu_down",
	MENU_LEFT = "menu_left", MENU_RIGHT = "menu_right",
	MENU_NEXT = "menu_next", MENU_PREV = "menu_prev",
	-- driving
	HANDBRAKE = "handbrake", VEHICLE_ACTION = "vehicle_action",
	VEHICLE_RAISE = "vehicle_raise", VEHICLE_LOWER = "vehicle_lower",
	-- reserved
	EXTRA0 = "extra0", EXTRA1 = "extra1", EXTRA2 = "extra2", EXTRA3 = "extra3",
	EXTRA4 = "extra4", EXTRA5 = "extra5", EXTRA6 = "extra6",
}

local KEYPREFIX = "options.input.keymap."

local CHANNELS = {
	{ key = "vr.enabled",  type = "bool",  default = true,  desc = "master on/off" },
	{ key = "vr.hands",   type = "bool",  default = true,  desc = "two-hand locomotion" },
	{ key = "vr.snap",    type = "float", default = 30,    desc = "turn snap degrees" },
	{ key = "vr.scale",   type = "float", default = 1.0,   desc = "movement speed scale" },
	{ key = "vr.deadzone",type = "float", default = 0.12,  desc = "stick deadzone" },
	{ key = "vr.debug",   type = "bool",  default = false, desc = "overlay" },
}

local state = {
	enabled = true,
	hands = true,
	snap = 30,
	scale = 1.0,
	deadzone = 0.12,
	debug = false,

	player = 0,
	bindings = {},      -- action -> key string, read back from the store
	injected = {},      -- action -> true while we hold it down
	pendingRelease = {},-- action -> true, pressed last frame, release next tick
	heldSince = {},     -- action -> frame number, for hold duration
	handYaw = 0,        -- accumulated snap turn, radians
	lastHmdOk = false,
	frames = 0,
}

-- ---------------------------------------------------------------------------
-- store helpers. Mods do NOT get a private store: the engine rewrites only the
-- key prefix, so everything we own lives under savegame.mod.teardownvr.<key>.
-- Keys outside [a-z0-9-], or starting with -/_, are silently dropped from the
-- save file while staying in memory, so keep the names boring.
-- ---------------------------------------------------------------------------

local function storeKey(k)
	return "savegame.mod.teardownvr." .. k
end

local function readConfig()
	for _, c in ipairs(CHANNELS) do
		local v
		if c.type == "bool" then
			v = HasKey(storeKey(c.key)) and GetBool(storeKey(c.key)) or c.default
		elseif c.type == "float" then
			v = HasKey(storeKey(c.key)) and GetFloat(storeKey(c.key)) or c.default
		else
			v = HasKey(storeKey(c.key)) and GetInt(storeKey(c.key)) or c.default
		end
		state[c.key:match("vr%.(.+)")] = v
	end
end

-- Rebind one action to one key, through the game's own remap store.
local function bind(action, key)
	if not action or not key or key == "" then
		return false
	end
	SetString(KEYPREFIX .. action, key)
	-- The game caches action icons in its UI table, so a rebind has to drop
	-- that cache or the UI keeps drawing the old glyphs. Guarded because this
	-- runs before the UI exists during init, and outside the game the table
	-- does not exist at all.
	if _G.Ui then
		_G.Ui.ActionIcons = nil
	end
	return true
end

local function unbind(action)
	if not action then
		return false
	end
	SetString(KEYPREFIX .. action, "")
	return true
end

-- Read back what the game currently has bound for an action.
local function bindingOf(action)
	local k = GetString(KEYPREFIX .. action)
	if k == nil or k == "" then
		return ""
	end
	return string.lower(k)
end

-- ---------------------------------------------------------------------------
-- input adapter. The native layer publishes controller state into the same
-- store; these are the reads. If nothing is publishing, the reads simply report
-- nothing pressed and the game is driven by whatever real hardware exists.
-- ---------------------------------------------------------------------------

local function channel(name)
	-- digital, 0/1
	return GetFloat(storeKey("in." .. name)) or 0
end

local function axis(name)
	return GetFloat(storeKey("axis." .. name)) or 0
end

local function dz(v)
	local a = math.abs(v)
	if a < state.deadzone then
		return 0
	end
	return (v / a) * ((a - state.deadzone) / (1 - state.deadzone))
end

-- Release bookkeeping. We cannot set an action down from Lua, so this tracks
-- INTENT: it is the state the native injector mirrors into the real input
-- layer.
--
-- A press must PERSIST for at least one frame before it can be released.
-- hold() followed immediately by release() inside the same tick would mark the
-- action down and up again within one frame, and the native side polling once
-- per frame would never observe it: the pulse would be invisible. So releases
-- are deferred to the next tick via pendingRelease, and a fresh press cancels a
-- pending one. This is a real bug class, not a test artefact - it is exactly
-- what a snap turn or a tool swap does.
local function hold(action)
	state.pendingRelease[action] = nil
	if not state.injected[action] then
		state.injected[action] = true
		bind(action, action)
		state.heldSince[action] = state.frames
	end
end

local function release(action)
	if state.injected[action] then
		state.pendingRelease[action] = true
	end
end

-- Called at the top of tick: a press scheduled last frame is now old enough to
-- be released, and any action that has not been re-pressed stays down.
local function serviceReleases()
	for action in pairs(state.pendingRelease) do
		state.injected[action] = nil
		state.pendingRelease[action] = nil
		state.heldSince[action] = nil
		unbind(action)
	end
end

-- ---------------------------------------------------------------------------
-- lifecycle
-- ---------------------------------------------------------------------------

-- GetLocalPlayer() raises "before init is not supported" if the mod starts
-- too early, so it is guarded and degrades to player 0.
local function localPlayer()
	local p = 0
	local ok = pcall(function() p = GetLocalPlayer() end)
	if not ok or p == nil then return 0 end
	return p
end

local function init()
	readConfig()
	state.player = localPlayer()
	-- snapshot the current scheme so the overlay and any debug output can show
	-- what the game thinks is bound, rather than what we assume.
	for _, a in pairs(ACTION) do
		state.bindings[a] = bindingOf(a)
	end
	state.lastHmdOk = true
end

local function tick(dt)
	if not state.enabled then
		return
	end
	-- GetTimeStep() is a fixed 1/60 inside update() but the real frame time in
	-- tick(), and the game calls tick() with no argument at all. So nil is the
	-- normal case, not an error case, and the fallback has to be the real
	-- frame time rather than a hardcoded constant.
	if dt == nil or dt <= 0 or dt > 1 then
		dt = GetTimeStep()
		if dt == nil or dt <= 0 or dt > 1 then
			-- a paused frame or a first frame; 1/60 is the engine's own fixed
			-- step so the accumulator cannot run away
			dt = 1 / 60
		end
	end
	state.frames = state.frames + 1
	serviceReleases()

	if state.hands then
		-- Snap turn. The accumulator is in radians and is advanced by the
		-- DEADZONED yaw, because raw stick noise is what makes snap turn
		-- drift. Firing resets only the amount consumed, so a large held
		-- rotation still turns repeatedly instead of once.
		local yaw = dz(axis("headyaw"))
		local threshold = math.rad(state.snap)
		if math.abs(yaw) > 0.001 then
			-- scaled by dt so the turn rate is the same at 60 and 144 Hz;
			-- without this, snap turn speed is a property of the framerate
			state.handYaw = state.handYaw + yaw * dt
		end
		if state.handYaw >= threshold then
			hold(ACTION.MENU_RIGHT)
			release(ACTION.MENU_RIGHT)
			state.handYaw = state.handYaw - threshold
		elseif state.handYaw <= -threshold then
			hold(ACTION.MENU_LEFT)
			release(ACTION.MENU_LEFT)
			state.handYaw = state.handYaw + threshold
		end
	end

	-- discrete buttons map straight through
	if channel("trigger") > 0.5 then
		hold(ACTION.USETOOL)
	else
		release(ACTION.USETOOL)
	end
	if channel("grip") > 0.5 then
		hold(ACTION.GRAB)
	else
		release(ACTION.GRAB)
	end
	if channel("a") > 0.5 then
		hold(ACTION.INTERACT)
	else
		release(ACTION.INTERACT)
	end
	if channel("b") > 0.5 then
		hold(ACTION.JUMP)
	else
		release(ACTION.JUMP)
	end

	-- report what the GAME sees, which is the only honest liveness signal
	local gameSeesAny = false
	for _, a in pairs(ACTION) do
		if InputDown(a) then
			gameSeesAny = true
			break
		end
	end
	state.lastHmdOk = gameSeesAny
end

local function draw()
	if not state.debug then
		return
	end
	UiPush()
	UiAlign("left top")
	UiFont("regular.ttf", 14)
	UiColor(1, 1, 1, 0.85)
	UiText(string.format("VR layer: %s  frames %d  dt %.4f",
		state.enabled and "on" or "off", state.frames, GetTimeStep()), 12, 12)
	UiText(string.format("bindings held: %d", (function()
		local n = 0
		for _ in pairs(state.injected) do n = n + 1 end
		return n
	end)()), 12, 30)
	UiPop()
end

-- The lifecycle callbacks above are declared as globals because that is the
-- shape the game expects -- but that is also the shape that collides. Every
-- mod in this folder defines init/tick/draw, so whichever file is probed LAST
-- wins and silently replaces the mod's own top-level entrypoint with an
-- unrelated module's callback. vrCandidates is iterated with pairs(), whose
-- order is undefined, so which file wins changes between runs.
--
-- Owning the global is correct for a stand-alone mod; owning it from a
-- library module is not. Keep the three names local, and publish the module
-- table under a namespaced global that main.lua can call explicitly. The
-- local copies are aliased below so the bodies stay readable.
local M = {
	ACTION = ACTION,
	state = state,
	bind = bind,
	unbind = unbind,
	bindingOf = bindingOf,
	readConfig = readConfig,
	-- the lifecycle callbacks are globals in the file, because that is how the
	-- game invokes them; expose them here too so a test does not have to reach
	-- into _G and so it fails loudly if they ever stop being defined
	init = init,
	tick = tick,
	draw = draw,
}

_G.vrinput = M

-- No `return M` here. merge.py concatenates this file with the others and with
-- main.lua, and a `return` in the middle of that concatenation makes everything
-- after it unreachable: the merged build would parse as "file ends right after
-- the return", which is exactly the `'<eof>' expected` error luac reports.
--
-- Assigning the global is enough. The test harness reads _G.vrinput, and the
-- game only ever calls the mod's own entrypoint.

end  -- end vrinput.lua scope

--==========================================================================
-- main.lua (entrypoint)
--==========================================================================

--[[===========================================================================
  main.lua -- Teardown VR: mod entrypoint.

  Installed as Teardown/mods/teardown_vr/main.lua, alongside info.txt.

  Responsibilities, in order:
    * load the sibling modules (with a probe -- see LOADING below),
    * own the frame loop: tick() drives detection and publication,
    * expose a VR settings overlay in draw(),
    * keep a heartbeat moving so the native side can tell "no events" from
      "Lua died".

  ---------------------------------------------------------------------------
  CALLBACK NAMES -- VERIFIED
  ---------------------------------------------------------------------------
  A mod whose entrypoint is main.lua uses the BARE global callbacks, not the
  client./server. prefixed ones. Confirmed against shipped mods:
    mods/speedometer/main.lua   -> function init() / tick() / update() / draw()
    mods/minigun/main.lua       -> function server.init() / server.tick(dt)
      (minigun is a tool mod and uses the prefixed form; both forms are seen,
       the bare form goes with main.lua)
  The client's own API stub file data/script_defs.luau uses client.tick /
  client.init / client.draw in its examples, which is the level-script form.
  This mod is a plain main.lua mod, so: init, tick, update, draw.

  The task brief asked for "init() and update(dt)". Both are implemented.
  The work is done in tick(), not update(), for one concrete reason that is
  documented in the API: script_defs.luau:150-155 states GetTimeStep()
  "Returns timestep of the last frame. If called from update, this returns the
  simulation time step, which is always one 60th of a second (0.0166667). If
  called from tick or draw it returns the actual time since last frame."
  Every detector here integrates over dt -- fall energy, footstep distance,
  rate limiters -- so it needs the real frame time. update() is implemented and
  does the frame-rate-independent work instead.

  ---------------------------------------------------------------------------
  LOADING -- ASSUMED, PROBED AT RUNTIME
  ---------------------------------------------------------------------------
  Whether dofile() can reach a mod's own .lua files is NOT established by any
  shipped mod. What is established is that "MOD/" is the mod's virtual asset
  root: shipped mods load "MOD/vox/...", "MOD/snd/...", "MOD/haptic/...",
  "MOD/img/...", "MOD/prefab/..." this way. The only dofile() calls in 2838
  shipped scripts use an absolute path derived from GetString("game.levelpath"),
  which is a different mechanism and does not apply to a main.lua mod.

  So this file probes rather than assumes: it tries each candidate path under
  pcall and uses the first that works. If none work the mod still loads and
  still publishes the camera block and heartbeat -- the native side gets a
  working channel minus the haptics detectors, which is a degraded but
  non-broken state, and the failure is reported on screen instead of being
  swallowed.

  If the probe fails in the real game, the fix is the one documented in
  docs/LUA_MOD_DESIGN.md: concatenate the modules into a single main.lua.
  lua/merge.py does exactly that.

  ---------------------------------------------------------------------------
  VERIFIED
  ---------------------------------------------------------------------------
  Everything main.lua itself calls:
      GetTime()                script_defs.luau:138
      GetTimeStep()            script_defs.luau:157
      DebugPrint(msg)          script_defs.luau:8731
      HasFile(path)            script_defs.luau:405
      GetBool / SetBool        script_defs.luau:705 / :693
      GetInt / SetInt          script_defs.luau:655 / :643
      GetString / SetString    script_defs.luau:730 / :718
      GetLocalPlayer()         script_defs.luau:5261
      IsPlayerValid(id)        script_defs.luau:5311
      UiPush / UiPop           -- verified in binary, used by every shipped
                                  HUD mod
      UiText / UiColor / UiWidth / UiHeight / UiTranslate / UiAlign
      UiTextButton / UiButtonText
  The Ui* batch is verified by presence in data/script_defs.luau and by
  2838 shipped scripts; exact pixel metrics and theming come from the game, so
  the overlay is laid out conservatively.

  ASSUMED:
  * UiTextButton's exact parameter list. Used in shipped mods as
    UiTextButton(text, x, y, w, h, ...) with a callback, but the stub returns
    the stub's own definition, so the trailing arguments (tooltip, style) are
    passed only where needed and the call is pcall-guarded.
  * That draw() is called even when the game's HUD is hidden (pause, respawn).
    If the overlay misbehaves in those states, the fix is to gate draw() on
    GetString("game.state") -- that key is read by shipped mods but is not in
    the stub file, so it is not used here.
============================================================================]]

--[[---------------------------------------------------------------------------
  Module loading. Order matters: the bus exists before anything can publish.

  The three modules are normally separate files and are pulled in by dofile().
  In the MERGED build (see merge.py) they are already concatenated above this
  point, so the probe must not gate them -- MERGED_BUILD is the marker merge.py
  writes, and when it is present the globals are checked but not loaded.
-------------------------------------------------------------------------------]]
vrModules = {
  bus     = false,
  haptics = false,
  camera  = false,
  input   = false,
}
vrMerged = (_G.MERGED_BUILD == true)

vrLoadErrors = {}

-- Candidates per module, in order. "MOD/..." is the mod virtual root; the bare
-- name is tried in case dofile resolves relative to the mod folder.
vrCandidates = {
  bus     = { "MOD/vrbus.lua",       "vrbus.lua" },
  haptics = { "MOD/vrhaptics.lua",   "vrhaptics.lua" },
  camera  = { "MOD/vrcamera.lua",    "vrcamera.lua" },
  input   = { "MOD/vrinput.lua",     "vrinput.lua" },
}

local function tryLoad(name, paths)
  for i = 1, #paths do
    local ok, err = pcall(dofile, paths[i])
    if ok then return true, paths[i] end
    vrLoadErrors[name] = tostring(err)
  end
  return false, nil
end

function vrLoadModules()
  -- The globals these files define. If a file loaded but did not define its
  -- global, that is a failure too, and is treated as one.
  local checks = {
    bus     = function() return VRBUS ~= nil end,
    haptics = function() return VRHAPTICS ~= nil end,
    camera  = function() return VRCAMERA ~= nil end,
    input   = function() return vrinput ~= nil end,
  }

  for name, paths in pairs(vrCandidates) do
    if vrMerged then
      -- Already inlined by merge.py. Just verify the global arrived.
      if checks[name]() then
        vrModules[name] = true
      else
        vrLoadErrors[name] = "merged build is missing global " .. name
        vrModules[name] = false
      end
    else
      local ok = tryLoad(name, paths)
      if ok and not checks[name]() then
        vrLoadErrors[name] = "loaded but global " .. name .. " undefined"
        ok = false
      end
      vrModules[name] = ok
    end
  end

  if vrModules.bus and vrModules.haptics and vrModules.camera and vrModules.input then
    vrModules.all = true
  else
    vrModules.all = false
  end
  return vrModules
end

--[[---------------------------------------------------------------------------
  State
-------------------------------------------------------------------------------]]
vr = nil          -- bus
vrhap = nil       -- haptics
vrcam = nil       -- camera
vrBooted = false
vrBootTime = 0
vrLastHb = 0
vrOverlay = false

--[[---------------------------------------------------------------------------
  vrEmergencyInit()
    Last-resort path. If the bus module could not be loaded by ANY path, the
    native side would otherwise have no channel at all -- not even the
    heartbeat it uses to tell "idle" from "dead".

    So if everything failed, install a minimal bus inline. It is not a
    replacement: no haptics, no camera. It publishes the version key, keeps
    the heartbeat moving, and keeps the event ring at zero so the native side
    has a defined thing to read. That is strictly better than silence, and it
    makes the failure diagnosable from the native log rather than invisible.

    VERIFIED: SetInt / GetInt / GetTime, all in data/script_defs.luau.
-------------------------------------------------------------------------------]]
function vrEmergencyInit()
  VRBUS = VRBUS or {}
  VRBUS.__index = VRBUS
  VRBUS_SLOTS = VRBUS_SLOTS or 16
  VRBUS_PROTOCOL_VERSION = VRBUS_PROTOCOL_VERSION or 1

  if VRBUS.new == nil then
    function VRBUS.new()
      local self = setmetatable({}, VRBUS)
      self.head, self.seq, self.count = 0, 0, 0
      self.enabled = true
      return self
    end
    -- Deliberately minimal: the native side only needs the heartbeat and a
    -- zero count. A real bus is never constructed in this path.
    function VRBUS.reset(self)
      self.head, self.seq, self.count = 0, 0, 0
      SetInt("vr.ev.version", VRBUS_PROTOCOL_VERSION)
      SetInt("vr.ev.count", 0)
      SetInt("vr.ev.head", 0)
      SetInt("vr.ev.seq", 0)
    end
    function VRBUS.emit(self) return false end
    function VRBUS.allow(self) return false end
    function VRBUS.setFloat(self, n, v) SetFloat("vr.val." .. n, v) end
    function VRBUS.getFloat(self, n) return GetFloat("vr.val." .. n) end
    function VRBUS.setBool(self, n, v) SetBool("vr.val." .. n, v) end
    function VRBUS.getBool(self, n) return GetBool("vr.val." .. n) end
    function VRBUS.publishCamera(self) SetInt("vr.cam.valid", 0) end
    function VRBUS.setHeartbeat(self, n) SetInt("vr.hb", n) end
  end

  vrModules.bus = true
  vrModules.all = false
  vrLog("[teardown_vr] MODULE LOAD FAILED - emergency bus only, haptics/camera off")
end

--[[---------------------------------------------------------------------------
  init()
    Called once when the mod loads. Build the object graph here so a failure
    in any one module cannot prevent the rest from being set up.
-------------------------------------------------------------------------------]]

--[[---------------------------------------------------------------------------
  vrLog(msg)
    GLOBAL, not local: merge.py wraps each module in `do ... end`, so a local
    helper here is invisible to init() in the merged build. VRBUS / VRHAPTICS /
    VRCAMERA / vrinput are globals for the same reason.

    VERIFIED 2026-09-28 in the live game: DebugPrint raises
    "Calling the DebugPrint API function before init is not supported" when it
    runs before the game is ready. It is an engine call, so pcall around the CALL
    catches it (unlike GetLocalPlayer, which throws while its ARGUMENTS are being
    evaluated). Logging is diagnostics, never control flow: if it cannot print,
    execution continues.
-------------------------------------------------------------------------------]]
function vrLog(msg)
  pcall(DebugPrint, tostring(msg))
end


--[[---------------------------------------------------------------------------
  tick()
    Per-frame work, on the real frame clock. This is where the detectors run
    and where the per-frame stereo block is published.
-------------------------------------------------------------------------------]]

--[[---------------------------------------------------------------------------
  update()
    Called at the fixed 60 Hz simulation rate. Kept deliberately empty of
    detector work (see the header on GetTimeStep); it exists so the mod
    satisfies the conventional entrypoint and has a place for simulation-rate
    logic later.
-------------------------------------------------------------------------------]]

--[[---------------------------------------------------------------------------
  draw()
    Status line plus a settings overlay.

    Ui model, verified against data/script_defs.luau and shipped mods:
      UiPush()/UiPop()               save/restore the draw state
      UiTranslate(x, y)              move the cursor
      UiText(text)                   draws AT THE CURSOR -- it takes no x/y.
                                      Returns w, h, endX, endY, linkId
                                      (:9771). Every shipped HUD mod uses
                                      UiTranslate then UiText.
      UiFont(path, size)             REQUIRES a TTF path; there is no nil
                                      default (:9707). "regular.ttf" and
                                      "bold.ttf" are the fonts shipped mods
                                      use. Size range documented 10..100.
      UiAlign("center middle")       affects the cursor origin
      UiColor(r,g,b,a)               r,g,b,a all 0..1 floats (:9196)
      UiRect(w, h)                   solid rect at the cursor (:9989)

    Every Ui call is inside pcall. A UI error must not break rendering, and
    the overlay is not worth a frame hitch.

  ASSUMED: the input identifiers. "menu_cancel", "up", "down", "r", "f", "tab"
  are the names shipped mods use (InputDown("up"), InputDown("interact"),
  InputDown("pause"), InputDown("menu_cancel") all appear in real code), but
  whether they are rebindable to something VR-friendly is untested. The
  whole input block is pcall-guarded, so a wrong identifier is a dead key
  rather than an error.
-------------------------------------------------------------------------------]]
local VR_FONT  = "regular.ttf"
local VR_BOLD  = "bold.ttf"


--[[---------------------------------------------------------------------------
  vrDrawOverlay()
    A plain label list. No buttons: UiTextButton draws at the cursor and
    returns whether it was clicked (:10333), which is usable but needs a
    cursor-relative layout, and the readouts are more useful than buttons for
    the first pass. Left in place deliberately simple.
-------------------------------------------------------------------------------]]
function vrDrawOverlay()
  local w = UiWidth()
  local h = UiHeight()
  local x = w * 0.5 - 220
  local y = h * 0.5 - 150

  UiFont(VR_FONT, 16)
  UiAlign("left")
  UiColor(0.0, 0.0, 0.0, 0.85)
  UiTranslate(x - 14, y - 34)
  UiRect(468, 300)
  UiResetColor()

  UiFont(VR_BOLD, 20)
  UiColor(1, 1, 1, 1)
  UiTranslate(x, y)
  UiText("Teardown VR - Lua layer")
  UiResetColor()

  local row = y + 30
  local function line(label, value, warn)
    UiFont(VR_FONT, 14)
    UiColor(0.72, 0.76, 0.80, 1)
    UiTranslate(x, row)
    UiText(label)
    if warn then UiColor(1.0, 0.45, 0.2, 1) else UiColor(1, 1, 1, 1) end
    UiTranslate(x + 190, row)
    UiText(value)
    UiResetColor()
    row = row + 20
  end

  if not vrModules.all then
    line("Modules loaded", "INCOMPLETE", true)
    for name, err in pairs(vrLoadErrors) do
      UiFont(VR_FONT, 11)
      UiColor(1.0, 0.55, 0.3, 1)
      UiTranslate(x, row)
      UiText(tostring(name) .. ": " .. tostring(err))
      row = row + 16
    end
    UiResetColor()
    return
  end

  line("Enabled", vrcam.enabled and "yes" or "no")
  line("Eye separation", string.format("%.1f mm  (scale %.2f)",
    vrcam.ipdScale * 64.0, vrcam.ipdScale))
  line("Horizontal FOV", string.format("%d deg  (10-170)", math.floor(vrcam.fov)))
  line("Near / far", string.format("%.2f / %.0f m", vrcam.near, vrcam.far))
  if vrhap ~= nil then
    line("Haptics", vrhap.playGameHaptics and "native + game pad" or "bus only")
    line("Events emitted", tostring(vrhap._stats.emitted))
    line("Rate limited", tostring(vrhap._stats.suppressed))
    line("Effect load fails", tostring(vrhap._stats.loadFail))
  end
  line("Heartbeat", tostring(math.floor(vrLastHb)))

  UiFont(VR_FONT, 11)
  UiColor(0.60, 0.65, 0.70, 1)
  UiTranslate(x, row + 8)
  UiText("up/down = FOV    r/f = IPD scale    tab = game pad haptics    menu_cancel = close")
  UiResetColor()

  -- Adjustments. Each is guarded; a bad identifier is a dead key, not a crash.
  if vrcam ~= nil then
    if pcall(InputPressed, "up") then vrAdjustFov(5) end
    if pcall(InputPressed, "down") then vrAdjustFov(-5) end
    if pcall(InputPressed, "r") then vrAdjustScale(0.05) end
    if pcall(InputPressed, "f") then vrAdjustScale(-0.05) end
  end
  if vrhap ~= nil and pcall(InputPressed, "tab") then
    vrhap.playGameHaptics = not vrhap.playGameHaptics
  end
end

function vrAdjustFov(d)
  vrcam.fov = vrcam.fov + d
  if vrcam.fov < VRCAMERA.FOV_MIN then vrcam.fov = VRCAMERA.FOV_MIN end
  if vrcam.fov > VRCAMERA.FOV_MAX then vrcam.fov = VRCAMERA.FOV_MAX end
  vrcam:saveSettings()
end

function vrAdjustScale(d)
  vrcam.ipdScale = vrcam.ipdScale + d
  if vrcam.ipdScale < 0.25 then vrcam.ipdScale = 0.25 end
  if vrcam.ipdScale > 3.0 then vrcam.ipdScale = 3.0 end
  vrcam:saveSettings()
end


--==========================================================================
-- entrypoint callbacks
--==========================================================================

function init()
  vrLoadModules()

  if not vrModules.bus then vrEmergencyInit() end

  if vrModules.bus then
    vr = VRBUS.new()
    -- Publish an empty ring immediately. Until this runs, the native side
    -- would read whatever the previous level left behind.
    vr:reset()
  end

  if vrModules.bus and vrModules.haptics then
    vrhap = VRHAPTICS.new(vr)
    -- Prime the sample state. Without this the first tick would see health
    -- 1.0 -> 0.0 and report a full-health damage event on level load.
    vrhap:init()
  end

  if vrModules.bus and vrModules.camera then
    vrcam = VRCAMERA.new(vr)
    vrcam:loadSettings()
  end

  if vr ~= nil then
    vr:setBool("mods", vrModules.all)
    vr:setFloat("haptics_enabled", (vrhap ~= nil) and 1.0 or 0.0)
  end

  -- The input layer keeps its own init because it reads config and snapshots
  -- the current keymap; that is its own concern, not the bus's.
  if vrinput ~= nil then
    pcall(function() vrinput.init() end)
  end

  vrLog("[teardown_vr] lua layer loaded; modules=" ..
        tostring(vrModules.bus) .. "/" .. tostring(vrModules.haptics) .. "/" ..
        tostring(vrModules.camera) .. "/" .. tostring(vrModules.input))
end


function tick(dt)
  if dt == nil or dt <= 0 then dt = GetTimeStep() end

  -- Guard against the pre-init frame and against a level teardown, where
  -- GetTime can go backwards and IsPlayerValid briefly fails.
  local okTime, now = pcall(GetTime)
  if not okTime then return end
  if now < vrBootTime - 1.0 then
    -- Time went backwards: the level restarted. Re-prime everything.
    vrBooted = false
  end
  if not vrBooted then
    vrBooted = true
    vrBootTime = now
    if vr ~= nil then vr:reset() end
    if vrhap ~= nil then vrhap:init() end
    if vrcam ~= nil then vrcam:loadSettings() end
  end

  if vrhap ~= nil then
    -- pcall the whole detector pass: a single wrong assumption inside one
    -- trigger must not take down the channel.
    pcall(VRHAPTICS.tick, vrhap, dt)
  end

  if vrcam ~= nil then
    pcall(VRCAMERA.tick, vrcam)
  end

  -- Input layer last, so it reads the same frame's controller state and its
  -- rebinds are visible to anything that runs after it. pcall-guarded for the
  -- same reason as the others: one bad input frame must not stop the bus.
  if vrinput ~= nil then
    pcall(function() vrinput.tick(dt) end)
  end

  -- Heartbeat, once a second.
  if vr ~= nil and (now - vrLastHb) >= 1.0 then
    vrLastHb = now
    vr:setHeartbeat(math.floor(now))
  end
end


function update(dt)
  -- Intentionally empty. See header comment.
end



function draw()
  if vr == nil then return end

  -- The overlay used to be toggled with InputPressed("menu_cancel") here. That
  -- is ESC, and because this draw() ran in the MENU's own context it swallowed
  -- the game's cancel key -- the user saw the mod's panel instead of the pause
  -- menu. A mod must not claim a key the game uses. The overlay is now shown
  -- only when explicitly armed from a console command, and defaults to off.

  pcall(function()
    UiPush()

    if not vrOverlay then
      -- Draw NOTHING by default. This used to print a status line on every
      -- frame, which meant the mod was painting over the game in the menu, in
      -- the pause menu and on the character-select screen. A mod that is merely
      -- loaded must be invisible: the store is the diagnostic channel, not the
      -- screen. Set vrOverlay from the console to inspect it.
      UiPop()
      return
    end

    vrDrawOverlay()
    UiPop()
  end)
end

